version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hamdia123
      MYSQL_DATABASE: incidents_db
      MYSQL_USER: incident_user
      MYSQL_PASSWORD: incident_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: incident-service
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://incident_user:incident_pass@db:3306/incidents_db
    volumes:
      - .:/app

volumes:
  db_data:
